from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
import json, numpy as np
import model_training_scipy as mts
import joblib as ja
from pydantic import BaseModel, Field
#https://scikit-learn.org/stable/modules/svm.html#classification


from fastapi import FastAPI

#define shape of input so it will be validated by fastapi and also visible in swagger documentation 
class IrisFeatures(BaseModel):
    sepal_length_cm: float = Field(..., description="Sepal length in cm", example=5.1)
    sepal_width_cm: float = Field(..., description="Sepal width in cm", example=3.5)
    petal_length_cm: float = Field(..., description="Petal length in cm", example=1.4)
    petal_width_cm: float = Field(..., description="Petal width in cm", example=0.2)

app = FastAPI()

@app.get("/")
#landing endpoint
async def root():
    """
        Welcome to the Predictive classification Model SVM by Mateusz Malinowski,

        Autogenerated Fastapi Documentation (swagger) can be found under /docs (you are currently here)

        Retrain Model (optional or if errors while training) using GET request to /retrain

        Preview Raw Data by going to /input/raw

        Predict by values by going to /input/predict_dict - please check documentation and sample schema for POST request body

        POST request body {"sepal_length_cm":0 , "sepal_width_cm: 0, "petal_length_cm": 0, "petal_width_cm": 0}

        example curl POST (command prompt) curl -X POST http://127.0.0.1:8000/input/predict_dict -H "accept: application/json" -H "Content-Type: application/json" -d "{\"sepal_length_cm\": 5.9, \"sepal_width_cm\": 3, \"petal_length_cm\": 5.1, \"petal_width_cm\": 1.8}"
    """
    return {
        "Message": "Welcome to the Predictive classification Model SVM",
        " NOTE": "For better UI experiences check /docs endpoint",
        " Autogenerated Fastapi Documentation (swagger)": "/docs",
        " Retrain Model (optional or if errors shile training)": "/retrain",
        " Preview Raw Data ": "/input/raw",
        " Predict by values ": "/input/predict_dict",
        " Input format for prediction ": "{sepal_length_cm, sepal_width_cm, petal_length_cm, petal_width_cm}",
        " Example POST request for prediction ": """curl -X POST http://127.0.0.1:8000/input/predict_dict -H "accept: application/json" -H "Content-Type: application/json" -d "{\"sepal_length_cm\": 5.9, \"sepal_width_cm\": 3, \"petal_length_cm\": 5.1, \"petal_width_cm\": 1.8}"""
        }

@app.get("/retrain")
def retrainModel():
    """
    This endpoint retrains the SVM model using the Iris dataset.
    
    It splits the data into training and testing sets, fits the model,
    and saves it for future predictions. Use this endpoint
    if you want to update the model or if you encounter errors during prediction, as it is generating
    model in the project directory (modelx.joblib) and if it is missing or corrupted, prediction will not work.
    It also regenerates target_names.joblib which is used to map numerical output to species names.
    """
    result = mts.retrain_model()
    return {"message": result}

@app.get("/input/raw")
def getRawData():
    """
    This endpoint returns the raw data from the Iris dataset used for training the SVM model.
    
    It provides the feature data, target labels, feature names, and target names in a structured format.
    
    The response includes:
    - data: A list of feature vectors for each sample in the dataset.
    - target: A list of numerical class labels corresponding to each sample.
    - feature_names: A list of feature names (e.g., sepal length, sepal width, etc.).
    - target_names: A list of target class names (e.g., setosa, versicolor, virginica).
    
    This endpoint is useful for understanding the data structure and for reference when making predictions.
    """
    iris = mts.get_raw_data()
    return iris

@app.post("/input/predict_dict")
def predictByValues(features: IrisFeatures):
    """
    Input fields:
    - sepal_length_cm: Length of the sepal in centimeters
    - sepal_width_cm: Width of the sepal in centimeters
    - petal_length_cm: Length of the petal in centimeters
    - petal_width_cm: Width of the petal in centimeters
    
    Returns:
    - prediction_class: Numeric class (0, 1, or 2)
    - prediction_name: Species name (setosa, versicolor, or virginica)
    """
    result =  mts.predict_by_values(features.dict())
    return {"message": result}

# @app.get("/input/raw")
# #preview data used for training
# def getRawData():
#     iris = mts.get_raw_data()
#     return iris

# @app.post("/input/predict_dict")
# def predictByValues(features: IrisFeatures):
#     return mts.predict_by_values(features.dict())